"""cria

Revision ID: 6878744f458b
Revises: d1307279b323
Create Date: 2020-12-25 19:16:30.897746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6878744f458b'
down_revision = 'd1307279b323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_cards', sa.Column('limit_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_cards', 'limit_day')
    # ### end Alembic commands ###
