"""empty message

Revision ID: 756ecb8840ba
Revises: 9e4ddb045358
Create Date: 2020-06-24 20:27:59.375121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756ecb8840ba'
down_revision = '9e4ddb045358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('history', sa.String(length=255), nullable=True),
    sa.Column('forecast_date', sa.Integer(), nullable=True),
    sa.Column('confirmation_date', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('confirmed_value', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['tb_banks.bank_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['tb_categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_invoices')
    # ### end Alembic commands ###
