"""empty message

Revision ID: 7d153dff95aa
Revises: 756ecb8840ba
Create Date: 2020-06-27 18:53:40.433779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d153dff95aa'
down_revision = '756ecb8840ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cards',
    sa.Column('card-id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Float(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card-id'], ['tb_banks.bank_id'], ),
    sa.PrimaryKeyConstraint('card-id')
    )
    op.add_column('tb_banks', sa.Column('type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_banks', 'type')
    op.drop_table('tb_cards')
    # ### end Alembic commands ###
