"""empty message

Revision ID: 7f10768af34a
Revises: 
Create Date: 2020-06-27 19:12:04.802466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f10768af34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_tb_users_user'), 'tb_users', ['user'], unique=True)
    op.create_table('tb_banks',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.user_id'], ),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('tb_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('go', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.user_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('tb_cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['tb_banks.bank_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('tb_invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('history', sa.String(length=255), nullable=True),
    sa.Column('forecast_date', sa.Integer(), nullable=True),
    sa.Column('confirmation_date', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('confirmed_value', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['tb_banks.bank_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['tb_categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_invoices')
    op.drop_table('tb_cards')
    op.drop_table('tb_categories')
    op.drop_table('tb_banks')
    op.drop_index(op.f('ix_tb_users_user'), table_name='tb_users')
    op.drop_table('tb_users')
    # ### end Alembic commands ###
