"""empty message

Revision ID: a03095c0a86d
Revises: c33d4ee56c6e
Create Date: 2020-06-21 21:54:43.068137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03095c0a86d'
down_revision = 'c33d4ee56c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_banks',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.user_id'], ),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_banks')
    # ### end Alembic commands ###
