"""Creat colum at category

Revision ID: d1307279b323
Revises: 7f10768af34a
Create Date: 2020-11-14 01:26:47.163038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1307279b323'
down_revision = '7f10768af34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_categories', sa.Column('remove_me', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_categories', 'remove_me')
    # ### end Alembic commands ###
